version: "3"
services:
  nginx:
    restart: always
    image: nginx
    ports:
      - "8098:80"
    volumes:
      - ./src:/src
      - ./local/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    restart: always
    container_name: php
    build:
      context: local/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/src
      - ./img:/src/img
      - ./local/nginx/php.ini:/usr/local/etc/php/php.ini
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - ./src/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3307:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8099:80"
    restart: always
    volumes:
      - ./local/php/php.ini:/usr/local/etc/php/php.ini